<?php

namespace App\Console\Commands;

use App\Support\SidebarSectionRegistry;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use RuntimeException;

class GenerateSidebarScopesCommand extends Command
{
    protected $signature = 'sidebar:generate-scopes
                            {--path= : Override the output path for the generated TypeScript file}';

    protected $description = 'Generate frontend sidebar scope constants from the backend registry.';

    public function handle(): int
    {
        $scopes = SidebarSectionRegistry::allScopes();
        $defaultScope = SidebarSectionRegistry::SCOPE_HOME;

        if (!in_array($defaultScope, $scopes, true)) {
            throw new RuntimeException('Default sidebar scope must be present in the exported scope list.');
        }

        $targetPath = $this->option('path')
            ? (string) $this->option('path')
            : base_path('../frontend/src/generated/sidebarScopes.ts');

        File::ensureDirectoryExists(dirname($targetPath));
        File::put($targetPath, $this->buildFileContents($scopes, $defaultScope));

        $this->info("Generated sidebar scopes: {$targetPath}");

        return self::SUCCESS;
    }

    /**
     * @param  array<int, string>  $scopes
     */
    private function buildFileContents(array $scopes, string $defaultScope): string
    {
        $scopeEntries = implode(",\n", array_map(
            static fn (string $scope): string => "  '".addslashes($scope)."'",
            $scopes
        ));

        $scopeObjectEntries = implode(",\n", array_map(
            static fn (string $scope): string => sprintf(
                "  %s: '%s'",
                strtoupper($scope),
                addslashes($scope)
            ),
            $scopes
        ));

        return implode("\n", [
            '// This file is generated by `php artisan sidebar:generate-scopes`. Do not edit manually.',
            '',
            'export const SIDEBAR_SCOPES = [',
            $scopeEntries,
            '] as const',
            '',
            'export type SidebarScope = typeof SIDEBAR_SCOPES[number]',
            '',
            'export const SIDEBAR_SCOPE = {',
            $scopeObjectEntries,
            '} as const satisfies Record<string, SidebarScope>',
            '',
            "export const DEFAULT_SIDEBAR_SCOPE: SidebarScope = '{$defaultScope}'",
            '',
            'export function isSidebarScope(v: unknown): v is SidebarScope {',
            "  return typeof v === 'string' && (SIDEBAR_SCOPES as readonly string[]).includes(v)",
            '}',
            '',
            'export function hasExplicitSidebarScope(v: unknown): v is SidebarScope {',
            "  if (typeof v !== 'string') return false",
            '  const trimmed = v.trim()',
            "  if (trimmed === '' || trimmed === 'undefined' || trimmed === 'null') return false",
            '  return isSidebarScope(trimmed)',
            '}',
            '',
            'export function normalizeSidebarScope(v: unknown): SidebarScope {',
            "  if (typeof v !== 'string') return DEFAULT_SIDEBAR_SCOPE",
            '  const trimmed = v.trim()',
            "  if (trimmed === '' || trimmed === 'undefined' || trimmed === 'null') return DEFAULT_SIDEBAR_SCOPE",
            '  return isSidebarScope(trimmed) ? trimmed : DEFAULT_SIDEBAR_SCOPE',
            '}',
            '',
        ]);
    }
}
