<script setup>
import { useAdminBlogPostsEditor } from "./blog/useAdminBlogPostsEditor";

const {
  activeTab,
  aiTagFallbackUsed,
  aiTagSuggestions,
  aiTagSuggestionsError,
  aiTagSuggestionsLoading,
  applySelectedAiTags,
  clearQuery,
  computeStatus,
  contentTabIssues,
  contentWordCount,
  coverPreview,
  data,
  deleting,
  error,
  form,
  formError,
  formatDate,
  hasQuery,
  hasSelectedAiTagSuggestions,
  isDirty,
  isEditing,
  isFocusActive,
  listDensity,
  loading,
  load,
  mediaTabIssues,
  metaTabIssues,
  nextPage,
  onCoverChange,
  onPerPageChange,
  page,
  pageRangeLabel,
  per_page,
  posts,
  previewBlocks,
  previewToc,
  prevPage,
  publishChecklist,
  publishNow,
  query,
  readTimeFor,
  remove,
  save,
  saveCoverOnly,
  saveStateLabel,
  saving,
  selectedId,
  selectedPost,
  selectedStatus,
  selectPost,
  setListDensity,
  setStatusFilter,
  showPreview,
  startNewPost,
  status,
  statusLabel,
  suggestAiTags,
  tagCount,
  tagsInput,
  titleLength,
  titleSlugPreview,
  toggleFocusMode,
} = useAdminBlogPostsEditor();
</script>
<template src="./blog/BlogPostsView.template.html"></template>

<style scoped src="./blog/BlogPostsView.css"></style>





