<?php

return [
    'interests' => [
        ['key' => 'meteory', 'label' => 'Meteory'],
        ['key' => 'komety', 'label' => 'Komety'],
        ['key' => 'planety', 'label' => 'Planety'],
        ['key' => 'mesiac', 'label' => 'Mesiac'],
        ['key' => 'zatmenia', 'label' => 'Zatmenia'],
        ['key' => 'galaxie', 'label' => 'Galaxie'],
        ['key' => 'astrofotografia', 'label' => 'Astrofotografia'],
        ['key' => 'iss', 'label' => 'ISS'],
        ['key' => 'novinky', 'label' => 'Astronomicke novinky'],
        ['key' => 'pozorovanie', 'label' => 'Pozorovanie oblohy'],
    ],
    'locations' => [
        ['label' => 'Bratislava, Slovensko', 'place_id' => 'sk:bratislava', 'lat' => 48.1486, 'lon' => 17.1077],
        ['label' => 'Kosice, Slovensko', 'place_id' => 'sk:kosice', 'lat' => 48.7164, 'lon' => 21.2611],
        ['label' => 'Presov, Slovensko', 'place_id' => 'sk:presov', 'lat' => 48.9984, 'lon' => 21.2339],
        ['label' => 'Zilina, Slovensko', 'place_id' => 'sk:zilina', 'lat' => 49.2231, 'lon' => 18.7394],
        ['label' => 'Nitra, Slovensko', 'place_id' => 'sk:nitra', 'lat' => 48.3076, 'lon' => 18.0845],
        ['label' => 'Banska Bystrica, Slovensko', 'place_id' => 'sk:banska-bystrica', 'lat' => 48.7363, 'lon' => 19.1462],
        ['label' => 'Trnava, Slovensko', 'place_id' => 'sk:trnava', 'lat' => 48.3774, 'lon' => 17.5872],
        ['label' => 'Trencin, Slovensko', 'place_id' => 'sk:trencin', 'lat' => 48.8945, 'lon' => 18.0444],
        ['label' => 'Martin, Slovensko', 'place_id' => 'sk:martin', 'lat' => 49.0665, 'lon' => 18.9239],
        ['label' => 'Poprad, Slovensko', 'place_id' => 'sk:poprad', 'lat' => 49.0557, 'lon' => 20.2980],
        ['label' => 'Prievidza, Slovensko', 'place_id' => 'sk:prievidza', 'lat' => 48.7745, 'lon' => 18.6275],
        ['label' => 'Zvolen, Slovensko', 'place_id' => 'sk:zvolen', 'lat' => 48.5775, 'lon' => 19.1250],
        ['label' => 'Povazska Bystrica, Slovensko', 'place_id' => 'sk:povazska-bystrica', 'lat' => 49.1215, 'lon' => 18.4217],
        ['label' => 'Michalovce, Slovensko', 'place_id' => 'sk:michalovce', 'lat' => 48.7543, 'lon' => 21.9195],
        ['label' => 'Spisska Nova Ves, Slovensko', 'place_id' => 'sk:spisska-nova-ves', 'lat' => 48.9446, 'lon' => 20.5615],
        ['label' => 'Komarno, Slovensko', 'place_id' => 'sk:komarno', 'lat' => 47.7577, 'lon' => 18.1287],
        ['label' => 'Levice, Slovensko', 'place_id' => 'sk:levice', 'lat' => 48.2156, 'lon' => 18.6071],
        ['label' => 'Humenne, Slovensko', 'place_id' => 'sk:humenne', 'lat' => 48.9371, 'lon' => 21.9162],
        ['label' => 'Bardejov, Slovensko', 'place_id' => 'sk:bardejov', 'lat' => 49.2926, 'lon' => 21.2750],
        ['label' => 'Liptovsky Mikulas, Slovensko', 'place_id' => 'sk:liptovsky-mikulas', 'lat' => 49.0820, 'lon' => 19.6125],
        ['label' => 'Ruzomberok, Slovensko', 'place_id' => 'sk:ruzomberok', 'lat' => 49.0748, 'lon' => 19.3075],
        ['label' => 'Piestany, Slovensko', 'place_id' => 'sk:piestany', 'lat' => 48.5948, 'lon' => 17.8288],
        ['label' => 'Lucenec, Slovensko', 'place_id' => 'sk:lucenec', 'lat' => 48.3321, 'lon' => 19.6691],
        ['label' => 'Topolcany, Slovensko', 'place_id' => 'sk:topolcany', 'lat' => 48.5636, 'lon' => 18.1672],
        ['label' => 'Pezinok, Slovensko', 'place_id' => 'sk:pezinok', 'lat' => 48.2894, 'lon' => 17.2669],
        ['label' => 'Cadca, Slovensko', 'place_id' => 'sk:cadca', 'lat' => 49.4350, 'lon' => 18.7888],
        ['label' => 'Dubnica nad Vahom, Slovensko', 'place_id' => 'sk:dubnica-nad-vahom', 'lat' => 48.9590, 'lon' => 18.1663],
        ['label' => 'Partizanske, Slovensko', 'place_id' => 'sk:partizanske', 'lat' => 48.6286, 'lon' => 18.3813],
        ['label' => 'Nove Zamky, Slovensko', 'place_id' => 'sk:nove-zamky', 'lat' => 47.9854, 'lon' => 18.1610],
        ['label' => 'Dunajska Streda, Slovensko', 'place_id' => 'sk:dunajska-streda', 'lat' => 47.9947, 'lon' => 17.6107],
        ['label' => 'Galanta, Slovensko', 'place_id' => 'sk:galanta', 'lat' => 48.1900, 'lon' => 17.7278],
        ['label' => 'Sala, Slovensko', 'place_id' => 'sk:sala', 'lat' => 48.1513, 'lon' => 17.8806],
        ['label' => 'Senec, Slovensko', 'place_id' => 'sk:senec', 'lat' => 48.2190, 'lon' => 17.4004],
        ['label' => 'Senica, Slovensko', 'place_id' => 'sk:senica', 'lat' => 48.6792, 'lon' => 17.3669],
        ['label' => 'Malacky, Slovensko', 'place_id' => 'sk:malacky', 'lat' => 48.4362, 'lon' => 17.0219],
        ['label' => 'Skalica, Slovensko', 'place_id' => 'sk:skalica', 'lat' => 48.8449, 'lon' => 17.2264],
        ['label' => 'Roznava, Slovensko', 'place_id' => 'sk:roznava', 'lat' => 48.6610, 'lon' => 20.5379],
        ['label' => 'Rimavska Sobota, Slovensko', 'place_id' => 'sk:rimavska-sobota', 'lat' => 48.3828, 'lon' => 20.0224],
        ['label' => 'Velky Krtis, Slovensko', 'place_id' => 'sk:velky-krtis', 'lat' => 48.2105, 'lon' => 19.3506],
        ['label' => 'Revuca, Slovensko', 'place_id' => 'sk:revuca', 'lat' => 48.6835, 'lon' => 20.1181],
        ['label' => 'Kezmarok, Slovensko', 'place_id' => 'sk:kezmarok', 'lat' => 49.1357, 'lon' => 20.4335],
        ['label' => 'Levoca, Slovensko', 'place_id' => 'sk:levoca', 'lat' => 49.0260, 'lon' => 20.5890],
        ['label' => 'Snina, Slovensko', 'place_id' => 'sk:snina', 'lat' => 48.9886, 'lon' => 22.1500],
        ['label' => 'Vranov nad Toplou, Slovensko', 'place_id' => 'sk:vranov-nad-toplou', 'lat' => 48.8884, 'lon' => 21.6848],
        ['label' => 'Trebisov, Slovensko', 'place_id' => 'sk:trebisov', 'lat' => 48.6286, 'lon' => 21.7195],
        ['label' => 'Svidnik, Slovensko', 'place_id' => 'sk:svidnik', 'lat' => 49.3082, 'lon' => 21.5714],
        ['label' => 'Stara Lubovna, Slovensko', 'place_id' => 'sk:stara-lubovna', 'lat' => 49.3009, 'lon' => 20.6894],
        ['label' => 'Dolny Kubin, Slovensko', 'place_id' => 'sk:dolny-kubin', 'lat' => 49.2095, 'lon' => 19.3034],
        ['label' => 'Namestovo, Slovensko', 'place_id' => 'sk:namestovo', 'lat' => 49.4079, 'lon' => 19.4803],
        ['label' => 'Bytca, Slovensko', 'place_id' => 'sk:bytca', 'lat' => 49.2212, 'lon' => 18.5588],
        ['label' => 'Kysucke Nove Mesto, Slovensko', 'place_id' => 'sk:kysucke-nove-mesto', 'lat' => 49.2981, 'lon' => 18.7845],
    ],
];
